"""empty message

Revision ID: 016af82e7a92
Revises: b14ea482fffd
Create Date: 2025-02-21 01:29:11.962858

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '016af82e7a92'
down_revision: Union[str, None] = 'b14ea482fffd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('unsuccesslog', sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('unsuccesslog', 'created_at')
    # ### end Alembic commands ###
