"""empty message

Revision ID: 0607c968c4bf
Revises: 40604bda6cbc
Create Date: 2025-03-18 13:23:45.833685

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0607c968c4bf'
down_revision: Union[str, None] = '40604bda6cbc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tickers', 'lot',
               existing_type=sa.INTEGER(),
               server_default=sa.text('1'),
               existing_nullable=True)
    op.drop_column('tickers', 'lot2')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tickers', sa.Column('lot2', sa.INTEGER(), autoincrement=False, nullable=True))
    op.alter_column('tickers', 'lot',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=True)
    # ### end Alembic commands ###
