"""empty message

Revision ID: 2549277ebbf5
Revises: c435fabcea65
Create Date: 2025-01-29 21:37:37.364555

"""
from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2549277ebbf5"
down_revision: str | None = "c435fabcea65"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "settings",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("log_delay", sa.Integer(), nullable=True),
        sa.Column("rare_tickers_limit", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_settings_id"), "settings", ["id"], unique=False)
    op.alter_column("tickers", "lot", existing_type=sa.INTEGER(), type_=sa.Float(), existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("tickers", "lot", existing_type=sa.Float(), type_=sa.INTEGER(), existing_nullable=True)
    op.drop_index(op.f("ix_settings_id"), table_name="settings")
    op.drop_table("settings")
    # ### end Alembic commands ###
