"""empty message

Revision ID: 2e7c1154c14b
Revises: 65fe90d145a8
Create Date: 2025-03-30 18:26:12.998102

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e7c1154c14b'
down_revision: Union[str, None] = '65fe90d145a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_log_end_deal_id'), 'log', ['end_deal_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_log_end_deal_id'), table_name='log')
    # ### end Alembic commands ###
