"""empty message

Revision ID: 355586ef728d
Revises: bae1a85b2940
Create Date: 2025-03-05 21:09:26.829626

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '355586ef728d'
down_revision: Union[str, None] = 'bae1a85b2940'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contacts', sa.Column('recipient', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contacts', 'recipient')
    # ### end Alembic commands ###
