"""empty message

Revision ID: 396add23c86b
Revises: c5875bc3b5a8
Create Date: 2025-01-20 02:34:21.601747

"""
from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "396add23c86b"
down_revision: str | None = "c5875bc3b5a8"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("log", sa.Column("ticker_id", sa.Integer(), nullable=True))
    op.create_foreign_key(None, "log", "tickers", ["ticker_id"], ["id"])
    op.drop_column("log", "ticker")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("log", sa.Column("ticker", sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, "log", type_="foreignkey")
    op.drop_column("log", "ticker_id")
    # ### end Alembic commands ###
