"""empty message

Revision ID: 40604bda6cbc
Revises: f2d23e1b4403
Create Date: 2025-03-18 13:17:29.678420

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '40604bda6cbc'
down_revision: Union[str, None] = 'f2d23e1b4403'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tickers', sa.Column('lot2', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tickers', 'lot2')
    # ### end Alembic commands ###
