"""empty message

Revision ID: 43f0eb1f65f6
Revises: d5fedec15b64
Create Date: 2025-03-02 01:05:51.239308

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '43f0eb1f65f6'
down_revision: Union[str, None] = 'd5fedec15b64'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alerts', sa.Column('trades_recovered', sa.String(), nullable=True))
    op.add_column('alerts', sa.Column('trades_recovered_channel', sa.String(), nullable=True))
    op.add_column('alerts', sa.Column('pings_recovered', sa.String(), nullable=True))
    op.add_column('alerts', sa.Column('pings_recovered_channel', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('alerts', 'pings_recovered_channel')
    op.drop_column('alerts', 'pings_recovered')
    op.drop_column('alerts', 'trades_recovered_channel')
    op.drop_column('alerts', 'trades_recovered')
    # ### end Alembic commands ###
