"""empty message

Revision ID: 4a98351a5b6c
Revises: a37d24ff13f3
Create Date: 2025-01-11 19:53:57.094297

"""
from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4a98351a5b6c"
down_revision: str | None = "a37d24ff13f3"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("traders", sa.Column("watch", sa.String(), server_default="new", nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("traders", "watch")
    # ### end Alembic commands ###
