"""empty message

Revision ID: 66efb35076c8
Revises: df12db09673b
Create Date: 2025-03-08 14:41:20.202530

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '66efb35076c8'
down_revision: Union[str, None] = 'df12db09673b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('traders_username_key', 'traders', type_='unique')
    op.create_index(op.f('ix_traders_username'), 'traders', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_traders_username'), table_name='traders')
    op.create_unique_constraint('traders_username_key', 'traders', ['username'])
    # ### end Alembic commands ###
