"""empty message

Revision ID: 713e1c114307
Revises: 066ecd0b2561
Create Date: 2025-01-29 23:14:06.713797

"""
from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "713e1c114307"
down_revision: str | None = "066ecd0b2561"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("tickers", sa.Column("end", sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("tickers", "end")
    # ### end Alembic commands ###
