"""empty message

Revision ID: 7885e466259d
Revises: 4cf482d31af4
Create Date: 2025-03-22 07:08:56.221337

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7885e466259d'
down_revision: Union[str, None] = '4cf482d31af4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('traderstatistics', sa.Column('start_date', sa.Date(), nullable=True))
    op.add_column('traderstatistics', sa.Column('end_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('traderstatistics', 'end_date')
    op.drop_column('traderstatistics', 'start_date')
    # ### end Alembic commands ###
