"""empty message

Revision ID: b14ea482fffd
Revises: c8b67b18a162
Create Date: 2025-02-14 00:45:04.471798

"""
from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b14ea482fffd"
down_revision: str | None = "c8b67b18a162"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "unsuccesslog",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("body", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_unsuccesslog_id"), "unsuccesslog", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_unsuccesslog_id"), table_name="unsuccesslog")
    op.drop_table("unsuccesslog")
    # ### end Alembic commands ###
