"""empty message

Revision ID: c4e01e221c2d
Revises: ff69f02ece18
Create Date: 2025-05-05 20:22:26.892698

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c4e01e221c2d'
down_revision: Union[str, None] = 'ff69f02ece18'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('settings', sa.Column('package_max_signals', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('settings', 'package_max_signals')
    # ### end Alembic commands ###
