"""empty message

Revision ID: c8b67b18a162
Revises: aabea3ff4aa1
Create Date: 2025-02-12 00:43:17.088176

"""
from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "c8b67b18a162"
down_revision: str | None = "aabea3ff4aa1"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "buffer",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("usernames", postgresql.ARRAY(sa.String()), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_buffer_id"), "buffer", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_buffer_id"), table_name="buffer")
    op.drop_table("buffer")
    # ### end Alembic commands ###
