"""empty message

Revision ID: fc5f550e5fab
Revises: 396add23c86b
Create Date: 2025-01-21 01:42:44.305678

"""
from typing import Union
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "fc5f550e5fab"
down_revision: str | None = "396add23c86b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("tickers", sa.Column("lot", sa.Integer(), nullable=True))
    op.add_column("tickers", sa.Column("type", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("tickers", "type")
    op.drop_column("tickers", "lot")
    # ### end Alembic commands ###
