"""empty message

Revision ID: fd013c350e2e
Revises: 4dc2cd4a1f2b
Create Date: 2025-03-20 10:41:23.331386

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fd013c350e2e'
down_revision: Union[str, None] = '4dc2cd4a1f2b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('traderstatistics', sa.Column('date_value', sa.String(), nullable=True))
    op.add_column('traderstatistics', sa.Column('period', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('traderstatistics', 'period')
    op.drop_column('traderstatistics', 'date_value')
    # ### end Alembic commands ###
