"""empty message

Revision ID: ff37b98a1d56
Revises: f922dd2566d3
Create Date: 2025-01-20 00:40:16.031682

"""
from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "ff37b98a1d56"
down_revision: str | None = "f922dd2566d3"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "log", "time", existing_type=postgresql.TIMESTAMP(), type_=sa.TIMESTAMP(timezone=True), existing_nullable=True
    )
    op.drop_index("ix_log_created_at", table_name="log")
    op.create_index(op.f("ix_log_time"), "log", ["time"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_log_time"), table_name="log")
    op.create_index("ix_log_created_at", "log", ["created_at"], unique=False)
    op.alter_column(
        "log", "time", existing_type=sa.TIMESTAMP(timezone=True), type_=postgresql.TIMESTAMP(), existing_nullable=True
    )
    # ### end Alembic commands ###
