"""empty message

Revision ID: ff69f02ece18
Revises: 752630b531f4
Create Date: 2025-05-02 22:28:09.385071

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ff69f02ece18'
down_revision: Union[str, None] = '752630b531f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tickers', sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tickers', 'is_active')
    # ### end Alembic commands ###
