"""empty message

Revision ID: 066ecd0b2561
Revises: 2549277ebbf5
Create Date: 2025-01-29 22:57:34.795492

"""
from typing import Union
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "066ecd0b2561"
down_revision: str | None = "2549277ebbf5"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("tickers", sa.Column("traders", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("tickers", "traders")
    # ### end Alembic commands ###
