"""empty message

Revision ID: 09f0e77d67b2
Revises: 5615bdc99a8d
Create Date: 2025-01-09 02:56:58.973609

"""
from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "09f0e77d67b2"
down_revision: str | None = "5615bdc99a8d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "code",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("code", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_code_id"), "code", ["id"], unique=False)
    op.create_table(
        "traders",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("username", sa.String(), nullable=True),
        sa.Column("code", sa.String(), nullable=True),
        sa.Column("status", sa.String(), nullable=True),
        sa.Column("subscribes", sa.Integer(), nullable=True),
        sa.Column("subscribers", sa.Integer(), nullable=True),
        sa.Column("portfolio", sa.Integer(), nullable=True),
        sa.Column("trades", sa.Integer(), nullable=True),
        sa.Column("profit", sa.Float(), nullable=True),
        sa.Column("badges", postgresql.ARRAY(sa.String()), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("code"),
    )
    op.create_index(op.f("ix_traders_id"), "traders", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_traders_id"), table_name="traders")
    op.drop_table("traders")
    op.drop_index(op.f("ix_code_id"), table_name="code")
    op.drop_table("code")
    # ### end Alembic commands ###
