"""empty message

Revision ID: 2121e0cf2d06
Revises: 4a98351a5b6c
Create Date: 2025-01-12 02:10:07.962946

"""
from typing import Union
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2121e0cf2d06"
down_revision: str | None = "4a98351a5b6c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("traders", sa.Column("count", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("traders", "count")
    # ### end Alembic commands ###
