"""empty message

Revision ID: 4a403455439f
Revises: dc9f64e1f4d2
Create Date: 2025-03-29 19:32:41.133073

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a403455439f'
down_revision: Union[str, None] = 'dc9f64e1f4d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('settings', sa.Column('count_private_stocks', sa.Boolean(), server_default=sa.text('false'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('settings', 'count_private_stocks')
    # ### end Alembic commands ###
