"""empty message

Revision ID: 56e5938a0783
Revises: 66efb35076c8
Create Date: 2025-03-08 16:41:38.892262

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '56e5938a0783'
down_revision: Union[str, None] = '66efb35076c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_traders_username_lower', 'traders', [sa.text('lower(username)')], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_traders_username_lower', table_name='traders')
    # ### end Alembic commands ###
