"""empty message

Revision ID: 69a856acc69b
Revises: 7885e466259d
Create Date: 2025-03-25 22:42:36.701472

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '69a856acc69b'
down_revision: Union[str, None] = '7885e466259d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('log', sa.Column('closed', sa.Boolean(), nullable=True))
    op.add_column('log', sa.Column('profit', sa.Float(), nullable=True))
    op.add_column('log', sa.Column('yield_', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('log', 'yield_')
    op.drop_column('log', 'profit')
    op.drop_column('log', 'closed')
    # ### end Alembic commands ###
