"""empty message

Revision ID: 82e9ba6c6556
Revises: fc5f550e5fab
Create Date: 2025-01-22 21:41:50.396717

"""
from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "82e9ba6c6556"
down_revision: str | None = "fc5f550e5fab"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("tickers", sa.Column("trades", sa.Integer(), nullable=True))
    op.add_column("tickers", sa.Column("last_month_traders", sa.Integer(), nullable=True))
    op.add_column("tickers", sa.Column("last_month", sa.Integer(), nullable=True))
    op.add_column("tickers", sa.Column("last_week_traders", sa.Integer(), nullable=True))
    op.add_column("tickers", sa.Column("last_week", sa.Integer(), nullable=True))
    op.add_column("tickers", sa.Column("last_day", sa.Integer(), nullable=True))
    op.add_column("tickers", sa.Column("last_day_traders", sa.Integer(), nullable=True))
    op.add_column("tickers", sa.Column("last_hour_traders", sa.Integer(), nullable=True))
    op.add_column("tickers", sa.Column("last_hour", sa.Integer(), nullable=True))
    op.add_column("tickers", sa.Column("last_trade_price", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("tickers", "last_trade_price")
    op.drop_column("tickers", "last_hour")
    op.drop_column("tickers", "last_hour_traders")
    op.drop_column("tickers", "last_day_traders")
    op.drop_column("tickers", "last_day")
    op.drop_column("tickers", "last_week")
    op.drop_column("tickers", "last_week_traders")
    op.drop_column("tickers", "last_month")
    op.drop_column("tickers", "last_month_traders")
    op.drop_column("tickers", "trades")
    # ### end Alembic commands ###
