"""empty message

Revision ID: 8a9ec23676c7
Revises: 09f0e77d67b2
Create Date: 2025-01-11 02:58:24.861236

"""
from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8a9ec23676c7"
down_revision: str | None = "09f0e77d67b2"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_code_id", table_name="code")
    op.drop_table("code")
    op.add_column("log", sa.Column("user_id", sa.Integer(), nullable=True))
    op.add_column("log", sa.Column("price", sa.Float(), nullable=True))
    op.add_column("log", sa.Column("currency", sa.String(), nullable=True))
    op.add_column("log", sa.Column("operation", sa.String(), nullable=True))
    op.create_foreign_key(None, "log", "traders", ["user_id"], ["id"])
    op.create_unique_constraint(None, "traders", ["username"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "traders", type_="unique")
    op.drop_constraint(None, "log", type_="foreignkey")
    op.drop_column("log", "operation")
    op.drop_column("log", "currency")
    op.drop_column("log", "price")
    op.drop_column("log", "user_id")
    op.create_table(
        "code",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("code", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint("id", name="code_pkey"),
    )
    op.create_index("ix_code_id", "code", ["id"], unique=False)
    # ### end Alembic commands ###
