"""empty message

Revision ID: 92a1904c3033
Revises: fe76a5bb39ae
Create Date: 2025-01-19 02:34:05.872715

"""
from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "92a1904c3033"
down_revision: str | None = "fe76a5bb39ae"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tickers",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_tickers_id"), "tickers", ["id"], unique=False)
    op.add_column("logsactivity", sa.Column("hour00", sa.Integer(), nullable=True))
    op.add_column("logsactivity", sa.Column("hour01", sa.Integer(), nullable=True))
    op.add_column("logsactivity", sa.Column("hour02", sa.Integer(), nullable=True))
    op.add_column("logsactivity", sa.Column("hour03", sa.Integer(), nullable=True))
    op.add_column("logsactivity", sa.Column("hour04", sa.Integer(), nullable=True))
    op.add_column("logsactivity", sa.Column("hour05", sa.Integer(), nullable=True))
    op.add_column("logsactivity", sa.Column("hour06", sa.Integer(), nullable=True))
    op.add_column("logsactivity", sa.Column("hour07", sa.Integer(), nullable=True))
    op.add_column("logsactivity", sa.Column("hour08", sa.Integer(), nullable=True))
    op.add_column("logsactivity", sa.Column("hour09", sa.Integer(), nullable=True))
    op.add_column("logsactivity", sa.Column("hour10", sa.Integer(), nullable=True))
    op.add_column("logsactivity", sa.Column("hour11", sa.Integer(), nullable=True))
    op.add_column("logsactivity", sa.Column("hour12", sa.Integer(), nullable=True))
    op.add_column("logsactivity", sa.Column("hour13", sa.Integer(), nullable=True))
    op.add_column("logsactivity", sa.Column("hour14", sa.Integer(), nullable=True))
    op.add_column("logsactivity", sa.Column("hour15", sa.Integer(), nullable=True))
    op.add_column("logsactivity", sa.Column("hour16", sa.Integer(), nullable=True))
    op.add_column("logsactivity", sa.Column("hour17", sa.Integer(), nullable=True))
    op.add_column("logsactivity", sa.Column("hour18", sa.Integer(), nullable=True))
    op.add_column("logsactivity", sa.Column("hour19", sa.Integer(), nullable=True))
    op.add_column("logsactivity", sa.Column("hour20", sa.Integer(), nullable=True))
    op.add_column("logsactivity", sa.Column("hour21", sa.Integer(), nullable=True))
    op.add_column("logsactivity", sa.Column("hour22", sa.Integer(), nullable=True))
    op.add_column("logsactivity", sa.Column("hour23", sa.Integer(), nullable=True))
    op.drop_column("logsactivity", "last_hour")
    op.drop_column("logsactivity", "time")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("logsactivity", sa.Column("time", postgresql.TIME(), autoincrement=False, nullable=True))
    op.add_column("logsactivity", sa.Column("last_hour", sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column("logsactivity", "hour23")
    op.drop_column("logsactivity", "hour22")
    op.drop_column("logsactivity", "hour21")
    op.drop_column("logsactivity", "hour20")
    op.drop_column("logsactivity", "hour19")
    op.drop_column("logsactivity", "hour18")
    op.drop_column("logsactivity", "hour17")
    op.drop_column("logsactivity", "hour16")
    op.drop_column("logsactivity", "hour15")
    op.drop_column("logsactivity", "hour14")
    op.drop_column("logsactivity", "hour13")
    op.drop_column("logsactivity", "hour12")
    op.drop_column("logsactivity", "hour11")
    op.drop_column("logsactivity", "hour10")
    op.drop_column("logsactivity", "hour09")
    op.drop_column("logsactivity", "hour08")
    op.drop_column("logsactivity", "hour07")
    op.drop_column("logsactivity", "hour06")
    op.drop_column("logsactivity", "hour05")
    op.drop_column("logsactivity", "hour04")
    op.drop_column("logsactivity", "hour03")
    op.drop_column("logsactivity", "hour02")
    op.drop_column("logsactivity", "hour01")
    op.drop_column("logsactivity", "hour00")
    op.drop_index(op.f("ix_tickers_id"), table_name="tickers")
    op.drop_table("tickers")
    # ### end Alembic commands ###
