"""empty message

Revision ID: a37d24ff13f3
Revises: 8a9ec23676c7
Create Date: 2025-01-11 16:20:51.543174

"""
from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a37d24ff13f3"
down_revision: str | None = "8a9ec23676c7"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("log", sa.Column("ticker", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("log", "ticker")
    # ### end Alembic commands ###
