"""empty message

Revision ID: c435fabcea65
Revises: 82e9ba6c6556
Create Date: 2025-01-23 16:39:40.495752

"""
from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c435fabcea65"
down_revision: str | None = "82e9ba6c6556"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("traders", sa.Column("last_update", sa.TIMESTAMP(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("traders", "last_update")
    # ### end Alembic commands ###
