"""empty message

Revision ID: d5fedec15b64
Revises: 016af82e7a92
Create Date: 2025-02-26 22:58:48.061654

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd5fedec15b64'
down_revision: Union[str, None] = '016af82e7a92'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_log', sa.String(), nullable=True),
    sa.Column('first_log_channel', sa.String(), nullable=True),
    sa.Column('second_log', sa.String(), nullable=True),
    sa.Column('second_log_channel', sa.String(), nullable=True),
    sa.Column('first_ping', sa.String(), nullable=True),
    sa.Column('first_ping_channel', sa.String(), nullable=True),
    sa.Column('second_ping', sa.String(), nullable=True),
    sa.Column('second_ping_channel', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alerts_id'), 'alerts', ['id'], unique=False)
    op.create_table('contacts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('channel', sa.String(), nullable=True),
    sa.Column('contact', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contacts_id'), 'contacts', ['id'], unique=False)
    op.create_table('schedulerrule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('day_l', sa.String(), nullable=True),
    sa.Column('day_r', sa.String(), nullable=True),
    sa.Column('hour_l', sa.Integer(), nullable=True),
    sa.Column('hour_r', sa.Integer(), nullable=True),
    sa.Column('minute_l', sa.Integer(), nullable=True),
    sa.Column('minute_r', sa.Integer(), nullable=True),
    sa.Column('interval1', sa.Integer(), nullable=True),
    sa.Column('interval2', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_schedulerrule_id'), 'schedulerrule', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_schedulerrule_id'), table_name='schedulerrule')
    op.drop_table('schedulerrule')
    op.drop_index(op.f('ix_contacts_id'), table_name='contacts')
    op.drop_table('contacts')
    op.drop_index(op.f('ix_alerts_id'), table_name='alerts')
    op.drop_table('alerts')
    # ### end Alembic commands ###
