"""empty message

Revision ID: dc9f64e1f4d2
Revises: 1c88673bdc36
Create Date: 2025-03-29 19:09:54.719109

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dc9f64e1f4d2'
down_revision: Union[str, None] = '1c88673bdc36'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('settings', sa.Column('count_stocks', sa.Boolean(), server_default=sa.text('false'), nullable=True))
    op.add_column('settings', sa.Column('count_futures', sa.Boolean(), server_default=sa.text('false'), nullable=True))
    op.add_column('settings', sa.Column('count_etfs', sa.Boolean(), server_default=sa.text('false'), nullable=True))
    op.add_column('settings', sa.Column('count_bonds', sa.Boolean(), server_default=sa.text('false'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('settings', 'count_bonds')
    op.drop_column('settings', 'count_etfs')
    op.drop_column('settings', 'count_futures')
    op.drop_column('settings', 'count_stocks')
    # ### end Alembic commands ###
