"""empty message

Revision ID: df12db09673b
Revises: 355586ef728d
Create Date: 2025-03-07 15:26:23.712075

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'df12db09673b'
down_revision: Union[str, None] = '355586ef728d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('servererrors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('log', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_servererrors_id'), 'servererrors', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_servererrors_id'), table_name='servererrors')
    op.drop_table('servererrors')
    # ### end Alembic commands ###
