"""empty message

Revision ID: f922dd2566d3
Revises: 248eebffbfc0
Create Date: 2025-01-20 00:26:07.590649

"""
from typing import Union
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f922dd2566d3"
down_revision: str | None = "248eebffbfc0"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("log_user_id_fkey", "log", type_="foreignkey")
    op.create_foreign_key(None, "log", "traders", ["user_id"], ["id"], ondelete="CASCADE")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "log", type_="foreignkey")
    op.create_foreign_key("log_user_id_fkey", "log", "traders", ["user_id"], ["id"])
    # ### end Alembic commands ###
